### ISSUE TITLE
`neutron` benchmarks: all fits are failing on nightly

### ISSUE THREAD

**Issue by veprbl** [eic/physics_benchmarks#32]
https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/jobs/3764372#L112

cc @sebouh137

**Comment by sebouh137** [comment]
@veprbl I was able to get this to pass on my local computer, but I had forgotten that I had made some changes to the EICrecon (some of the parameters of the HEXPLIT and topo clustering) which were not merged into the main.  I have now put in a pull request that includes these updates ( https://github.com/eic/EICrecon/pull/1611 ).  When I run the benchmark locally with main, I reproduce your same problem, so I think this patch will fix the issue.  Let me know if this works.  
Thanks,
Sebouh.

**Comment by veprbl** [comment]
Thanks! The current state when if fails because something wasn't right is pretty good already. Would be nice to do it more gracefully with more indication on what's actually going wrong.
